LocaAmigos/Models/Jogos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LocaAmigos.Models
{
    public class Jogos : Entidade
    {
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Display(Name = "Tipo do Jogo")]
        public string tipojogo { get; set; }
        [Display(Name = "Liberado")]
        public bool ativo { get; set; }
    }
}

LocaAmigos/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LocaAmigos.Data;
using LocaAmigos.Models;
using Microsoft.AspNetCore.Authorization;

namespace LocaAmigos.Controllers
{
    [Authorize]
    public class JogosController : Controller
    {
        private readonly BdContext _context;

        public JogosController(BdContext context)
        {
            _context = context;
        }

        // GET: Jogos
        public async Task<IActionResult> Index()
        {
            return View(await _context.jogos.ToListAsync());
        }
        [HttpGet]
        public async Task<IActionResult> _GetListaGamesLiberados(string nome)
        {
            nome = (nome == null ? "" : nome);
            return View(await _context.jogos
                .Where(w => w.ativo && w.nome.Contains(nome))
                .ToListAsync());
        }

        public IActionResult Reservar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogos = _context.jogos
                .FirstOrDefault(m => m.id == id);
            if (jogos == null)
            {
                return NotFound();
            }

            return View(jogos);
        }


        // GET: Jogos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogos = await _context.jogos
                .FirstOrDefaultAsync(m => m.id == id);
            if (jogos == null)
            {
                return NotFound();
            }

            return View(jogos);
        }

        // GET: Jogos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jogos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("nome,tipojogo,ativo,id,created,update,remove")] Jogos jogos)
        {
            if (ModelState.IsValid)
            {
                jogos.created = DateTime.Now;
                jogos.update = new DateTime(1, 1, 1);
                jogos.remove = new DateTime(1, 1, 1);
                _context.Add(jogos);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jogos);
        }

        // GET: Jogos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogos = await _context.jogos.FindAsync(id);
            if (jogos == null)
            {
                return NotFound();
            }
            return View(jogos);
        }

        // POST: Jogos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("nome,tipojogo,ativo,id,created,update,remove")] Jogos jogos)
        {
            if (id != jogos.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogosExists(jogos.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jogos);
        }

        // GET: Jogos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jogos = await _context.jogos
                .FirstOrDefaultAsync(m => m.id == id);
            if (jogos == null)
            {
                return NotFound();
            }

            return View(jogos);
        }

        // POST: Jogos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jogos = await _context.jogos.FindAsync(id);
            _context.jogos.Remove(jogos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JogosExists(int id)
        {
            return _context.jogos.Any(e => e.id == id);
        }
    }
}

LocaAmigos/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LocaAmigos.Data;
using LocaAmigos.Models;
using LocaAmigos.Models.DVO;
using Microsoft.AspNetCore.Authorization;

namespace LocaAmigos.Controllers
{
    [Authorize]
    public class PessoasController : Controller
    {
        private readonly BdContext _context;

        public PessoasController(BdContext context)
        {
            _context = context;
        }
        #region CRUD
        // GET: Pessoas
        public async Task<IActionResult> Index()
        {
            return View(await _context.pessoa.ToListAsync());
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.pessoa
                .FirstOrDefaultAsync(m => m.id == id);
            if (pessoa == null)
            {
                return NotFound();
            }
            var usuario = _context.usuario.FirstOrDefault(s => s.Pessoa.id == id);
            var pessoaVO = new PessoaVO()
            {
                id = pessoa.id,
                Nome = pessoa.nome,
                NomeCompleto = pessoa.nomecompleto,
                DataNascimento = pessoa.datanascimento,
                created = pessoa.created,
                Email = usuario.email,
                Ativo = usuario.ativo
            };

            return View(pessoaVO);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,NomeCompleto,DataNascimento,Email,Senha,id,created,update,remove")] PessoaVO pessoaVO)
        {
            if (ModelState.IsValid)
            {
                var pessoa = new Pessoa() 
                { 
                    created = DateTime.Now,
                    update = new DateTime(1, 1, 1),
                    remove = new DateTime(1, 1, 1),
                    nome = pessoaVO.Nome,
                    nomecompleto = pessoaVO.NomeCompleto,
                    datanascimento = pessoaVO.DataNascimento
                };
                _context.Add(pessoa);
                var usuario = new Usuario()
                {
                    created = DateTime.Now,
                    update = new DateTime(1, 1, 1),
                    remove = new DateTime(1, 1, 1),
                    email = pessoaVO.Email,
                    senha = pessoaVO.Senha,
                    ativo = true,
                    Pessoa = pessoa
                };
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoaVO);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.pessoa.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            var usuario = _context.usuario.FirstOrDefault(s => s.Pessoa.id == id);
            var pessoaVO = new PessoaVO()
            {
                id = pessoa.id,
                Nome = pessoa.nome,
                NomeCompleto = pessoa.nomecompleto,
                DataNascimento = pessoa.datanascimento,
                created = pessoa.created,
                Email = (usuario != null ? usuario.email : "" ),
                Ativo = (usuario != null ? usuario.ativo : true)
            };
            return View(pessoaVO);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,NomeCompleto,DataNascimento,Email,Senha,id,created,update,remove")] PessoaVO pessoaVO)
        {
            if (id != pessoaVO.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var pessoa = _context.pessoa.FirstOrDefault(s => s.id == pessoaVO.id);
                    pessoa.update = DateTime.Now;
                    pessoa.nome = pessoaVO.Nome;
                    pessoa.nomecompleto = pessoaVO.NomeCompleto;
                    pessoa.datanascimento = pessoaVO.DataNascimento;
                    _context.Update(pessoa);
                    var usuario = _context.usuario.FirstOrDefault(s => s.Pessoa.id == pessoaVO.id);
                    usuario.email = pessoaVO.Email;
                    usuario.senha = pessoaVO.Senha;
                    usuario.ativo = pessoaVO.Ativo;
                    usuario.update = DateTime.Now;
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaExists(pessoaVO.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoaVO);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.pessoa
                .FirstOrDefaultAsync(m => m.id == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            var usuario = _context.usuario.FirstOrDefault(s => s.Pessoa.id == id);
            var pessoaVO = new PessoaVO()
            {
                id = pessoa.id,
                Nome = pessoa.nome,
                NomeCompleto = pessoa.nomecompleto,
                DataNascimento = pessoa.datanascimento,
                created = pessoa.created,
                Email = (usuario != null ? usuario.email : ""),
                Ativo = (usuario != null ? usuario.ativo : true)
            };
            return View(pessoaVO);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoa = await _context.pessoa.FindAsync(id);
            var usuario = _context.usuario.FirstOrDefault(s => s.Pessoa.id == pessoa.id);
            _context.usuario.Remove(usuario);
            _context.pessoa.Remove(pessoa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoaExists(int id)
        {
            return _context.pessoa.Any(e => e.id == id);
        }
        #endregion
        [HttpGet]
        public async Task<IActionResult> _GetListaPessoas(string nome="")
        {
            return PartialView(_context.pessoa.Where(w=>w.nomecompleto.Contains((nome==null?"":nome))).ToList());
        }
    }
}

LocaAmigos/Views/Jogos/Create.cshtml
@model LocaAmigos.Models.Jogos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Jogos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipojogo" class="control-label"></label>
                <input asp-for="tipojogo" class="form-control" />
                <span asp-validation-for="tipojogo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ativo" /> @Html.DisplayNameFor(model => model.ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LocaAmigos/Views/Jogos/Delete.cshtml
@model LocaAmigos.Models.Jogos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Jogos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipojogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipojogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ativo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LocaAmigos/Views/Jogos/Details.cshtml
@model LocaAmigos.Models.Jogos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Jogos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipojogo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipojogo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ativo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ativo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.created)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LocaAmigos/Views/Jogos/Edit.cshtml
@model LocaAmigos.Models.Jogos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Jogos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipojogo" class="control-label"></label>
                <input asp-for="tipojogo" class="form-control" />
                <span asp-validation-for="tipojogo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ativo" /> @Html.DisplayNameFor(model => model.ativo)
                </label>
            </div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LocaAmigos/Views/Jogos/Index.cshtml
@model IEnumerable<LocaAmigos.Models.Jogos>

@{
    ViewData["Title"] = "Index";
}


<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div>    
    @Html.Label("Pesquisar")
    <input type="text" id="txtPesquisar" onkeyup="getJogosFiltrado();" onchange="getJogosFiltrado();" />
</div>
<div id="TabelaGames">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tipojogo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ativo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.created)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.tipojogo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ativo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.created)
                    </td>
                    <td>
                        <a asp-action="Reservar" asp-route-id="@item.id">Reservar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<script type="text/javascript">

    function getJogosFiltrado() {
        var nome = document.getElementById("txtPesquisar").value;
        $.ajax({
        type: "GET",
            url: '@Url.Action("_GetListaGamesLiberados", "Jogos")',
            data: "nome="+ nome,
            success: function(d) {
            /* d is the HTML of the returned response */
                $("#TabelaGames").html(d); //replaces previous HTML with action
            }
        });
    }
</script>

LocaAmigos/Views/Jogos/Reservar.cshtml
@model LocaAmigos.Models.Jogos

@using (Html.BeginForm("Reservar", "Jogos", FormMethod.Post))
{
    @Html.Hidden("JogosId", Model.id)
    <div class="row">
        <div class="col-4">
            <h4>Jogo</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.nome)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.nome)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.tipojogo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.tipojogo)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.ativo)
                </dt>
                <dd class="col-sm-7">
                    @Html.DisplayFor(model => model.ativo)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.created)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.created)
                </dd>
            </dl>
        </div>
        <div class="col-4">
            <div>
                @Html.Label("Pesquisar")
                <input type="text" id="txtPesquisar" onchange="getPessoaFiltrado();" />
            </div>
            <div id="ListaPessoas">
            </div>

        </div>
        <div class="col-4">

        </div>
    </div>
}
<script type="text/javascript">
window.setTimeout(function () { getPessoaFiltrado();},1);
function getPessoaFiltrado() {
    var nome = document.getElementById("txtPesquisar").value;
    $.ajax({
    type: "GET",
        url: '@Url.Action("_GetListaPessoas", "Pessoas")',
        data: "nome="+ nome,
        success: function(d) {
        /* d is the HTML of the returned response */
            $("#ListaPessoas").html(d); //replaces previous HTML with action
        }
    });
}
</script>

LocaAmigos/Views/Jogos/_GetListaGamesLiberados.cshtml
@model IEnumerable<LocaAmigos.Models.Jogos>
@{ 
    Layout = null;
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipojogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ativo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.created)
            </th>
            <th>
                Ação
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipojogo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ativo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created)
                </td>
                <td>
                    <a asp-action="Reservar" asp-route-id="@item.id">Reservar</a>
                </td>
            </tr>
        }
    </tbody>
</table>